### ISSUE TITLE
In example add mime types

### ISSUE THREAD

**Issue by jackttcoms** [iamdual/uploader#1]
in example can you add mime type thanks

**Comment by iamdual** [comment]
Added. 

You can set mime types like this:
```
$upload->allowed_types(array("image/png", "image/jpeg"));
```

**Comment by jackttcoms** [comment]
Yeh, don't worry I discovered that! It was late, brain not working. Also I have added image dimentions option to the class if you wanna me to contribute? 👍  Great class!
